
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: demo
      RABBITMQ_DEFAULT_PASS: demo
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
  producer:
    build: ./events-producer
    depends_on: 
      rabbitmq:
        condition: service_healthy
        restart: true
    ports:
      - 9090:9090
    environment:
      RABBITMQ_URL: "rabbitmq:5672"
  consumer:
    build: ./events-consumer
    depends_on: 
      rabbitmq:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
    environment:
      RABBITMQ_URL: "rabbitmq:5672"
