server:
  port: 19091
  
spring:
  docker:
    compose:
			start:
			  arguments:
			    - --pull=${PULL_POLICY:missing}
					- --build
      stop:
        command: down
      file:
        - ../integration-compose.yml
      skip:
        in-tests: false