
services:
  kafka:
    pull_policy: always
    image: ghcr.io/opcal/kafka:2.13-3.9
    environment:
      KAFKA_CLUSTER_ID: AxUfivavQVGuQH2l4yfxCA
    entrypoint:
      - bash
      - -ec
      - | 
        sed -ir "s/^[#]*\s*advertised.listeners=.*/advertised.listeners=PLAINTEXT:\/\/kafka:9092,CONTROLLER:\/\/kafka:9093/" /opt/kafka/config/kraft/reconfig-server.properties
        
        cat /opt/kafka/config/kraft/reconfig-server.properties
        
        kafka-storage.sh format --standalone -t $${KAFKA_CLUSTER_ID} -c /opt/kafka/config/kraft/reconfig-server.properties
        kafka-server-start.sh /opt/kafka/config/kraft/reconfig-server.properties
    ports:
      - 9092:9092
      - 9093:9093
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9092"
      interval: 5s
      timeout: 5s
      retries: 3
  producer:
    build: ./kafka-bus-producer
    depends_on: 
      kafka:
        condition: service_healthy
        restart: true
    ports:
      - 9090:9090
    environment:
      KAFKA_SERVER: "kafka:9092"
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9090"
      interval: 5s
      timeout: 5s
      retries: 3
  consumer:
    build: ./kafka-bus-consumer
    depends_on: 
      kafka:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
    environment:
      KAFKA_SERVER: "kafka:9092"
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8080"
      interval: 5s
      timeout: 5s
      retries: 3
