server:
  port: 19091
  
spring:
  docker:
    compose:
      start:
        arguments:
        - '--force-recreate'
      stop:
        command: down
      file:
        - ../integration-compose.yml
      skip:
        in-tests: false