
server:
  port: 8080

spring:
  application:
    name: @artifactId@
  cloud:
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.value}
      trace:
        enabled: true
  rabbitmq:
    addresses: ${RABBITMQ_URL:127.0.0.1:5672}
    username: demo
    password: demo
    virtual-host: /
  docker:
    compose:
      stop:
        command: down
      file:
        - ../rabbitmq-compose.yml
      skip:
        in-tests: false